Repository dklog-team/dklog-admin-ui, pull requests merged in 2023-06, with the labels that each got.

#22 Feature/admin UI 17
  package-lock.json
  package.json
  src/api/core/request.js
  src/api/visitor.js
  src/components/visitor/VisitorChart.vue
  src/views/AdminHome.vue
Labels: feature

#24 Feature/admin UI 19
  src/api/student.js
  src/components/student/updateModal.vue
  src/routes/index.js
  src/views/RegisterStudent.vue
  src/views/StudentAdmin.vue
Labels: feature

#25 Feature/admin UI 21
  package-lock.json
  package.json
  src/api/post.js
  src/components/common/Pagination.vue
  src/views/PostAdmin.vue
  tailwind.config.js
Labels: feature

#20 Feature/admin UI 12
  src/api/post.js
  src/views/PostAdmin.vue
Labels: feature

#27 Feature/admin UI 26
  src/views/RegisterStudent.vue
  src/views/StudentAdmin.vue
Labels: feature

#29 Feature/admin UI 28
  src/api/member.js
  src/components/common/SideBar.vue
  src/components/student/memberModal.vue
  src/views/StudentAdmin.vue
Labels: feature

#33 Feature/admin UI 23
  src/api/post.js
  src/api/student.js
  src/components/common/SideBar.vue
  src/components/student/StudentAuthChart.vue
  src/components/visitor/VisitorChart.vue
  src/views/AdminHome.vue
Labels: feature

#37 Feature/admin 35
  src/components/student/memberModal.vue
  src/components/student/updateModal.vue
  src/views/StudentAdmin.vue
Labels: feature

#36 Feature/admin UI 31
  src/api/comment.js
  src/views/CommentAdmin.vue
Labels: feature

#40 Feature/admin-ui-32
  package-lock.json
  package.json
  src/api/image.js
  src/components/common/SideBar.vue
  src/main.js
  src/routes/index.js
  src/views/ImageAdmin.vue
  src/views/PostAdmin.vue
Labels: feature

#41 Feature/admin UI 34
  src/api/sms.js
  src/components/common/SideBar.vue
  src/components/modal/ShowSmsResultDataModal.vue
  src/routes/index.js
  src/views/SmsAdmin.vue
Labels: feature

#42 Feature/admin-ui-39
  package-lock.json
  package.json
  src/main.js
  src/views/PostAdmin.vue
  src/views/StudentAdmin.vue
Labels: feature

#46 Feature/admin-ui-43
  src/components/common/Pagination.vue
  src/views/ImageAdmin.vue
  src/views/PostAdmin.vue
Labels: feature

#45 Feature/admin UI 44
  src/views/StudentAdmin.vue
Labels: feature

#50 feature/admin ui 48
  src/views/PostAdmin.vue
Labels: feature

#49 Feature/admin UI 47
  src/views/SmsAdmin.vue
Labels: feature

#51 Feature/admin UI 38
  src/views/CommentAdmin.vue
Labels: feature

#53 Feature/admin UI 52
  src/components/student/memberModal.vue
  src/components/student/updateModal.vue
  src/views/RegisterStudent.vue
  src/views/StudentAdmin.vue
Labels: feature

#59 Feature/admin UI 58
  src/components/common/SideBar.vue
  src/routes/index.js
  src/views/AdminHome.vue
  src/views/StudentAdmin.vue
Labels: feature

#55 Feature/admin UI 54
  src/views/PostAdmin.vue
Labels: feature

#60 Feature/admin UI 57
  src/views/CommentAdmin.vue
Labels: bug

#63 Feature/admin UI 61
  .env.development
  .env.production
  src/App.vue
  src/api/core/request.js
  src/views/Login.vue
Labels: feature

#64 feat: 소스코드 수정
  src/views/Login.vue
Labels: feature

#68 Feature/admin UI 62
  src/views/ImageAdmin.vue
Labels: feature

#66 Feature/admin UI 65
  src/views/CommentAdmin.vue
Labels: feature

#69 Feature/admin UI 67
  src/api/admin.js
  src/api/core/request.js
  src/components/common/Header.vue
  src/store/auth.js
Labels: feature

#73 Feature/admin UI 72
  src/views/CommentAdmin.vue
  src/views/PostAdmin.vue
  src/views/SmsAdmin.vue
Labels: fix
